import { db, pool } from './index.ts';
import {
  departments,
  users,
  faculty,
  subjects,
  classrooms,
  leaveTypes,
  timetableSlots,
  leaveRequests,
  alternativeClasses,
  notifications,
  auditLogs,
} from './schema.ts';

export async function seedDatabase() {
  console.log('Initiating controlled Faculty360 database seed...');

  // 1. Departments
  console.log('Seeding departments...');
  await db.insert(departments).values([
    { id: 'dept-cse', code: 'CSE', name: 'Computer Science & Engineering', hodName: 'Dr. Rajesh Sharma', facultyCount: 38, attendanceRate: 96 },
    { id: 'dept-comm', code: 'COMM', name: 'Commerce & Accounting', hodName: 'Dr. Vandana Rao', facultyCount: 31, attendanceRate: 94 },
    { id: 'dept-mgmt', code: 'MGMT', name: 'Management Studies', hodName: 'Dr. Alok Verma', facultyCount: 29, attendanceRate: 93 },
    { id: 'dept-ece', code: 'ECE', name: 'Electronics & Communication', hodName: 'Dr. M. Srinivasan', facultyCount: 46, attendanceRate: 91 },
    { id: 'dept-mech', code: 'MECH', name: 'Mechanical Engineering', hodName: 'Dr. Hemant Joshi', facultyCount: 40, attendanceRate: 89 },
  ]).onConflictDoNothing();

  // 2. Demo Users & Profiles
  console.log('Seeding users...');
  await db.insert(users).values([
    {
      id: 'usr-owner',
      email: 'rct9096wgl@gmail.com',
      name: 'System Administrator',
      role: 'ADMIN',
      facultyId: 'ADMIN-SYS-001',
      departmentId: null,
      departmentName: 'Academic Administration & IT',
      designation: 'Chief Academic Administrator',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      phone: '+91 98000 00001',
      leaveCasual: 12,
      leaveMedical: 10,
      leaveEarned: 10,
      leaveTotal: 32,
    },
    {
      id: 'usr-rajesh',
      email: 'rajesh.sharma@takshashila.edu',
      name: 'Dr. Rajesh Sharma',
      role: 'HOD',
      facultyId: 'FAC-CSE-001',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      designation: 'Assoc. Professor & HOD',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      phone: '+91 98450 12345',
      leaveCasual: 6,
      leaveMedical: 4,
      leaveEarned: 2,
      leaveTotal: 12,
    },
    {
      id: 'usr-admin',
      email: 'admin@faculty360.demo',
      name: 'Dr. K. S. Somnath',
      role: 'ADMIN',
      facultyId: 'ADMIN-001',
      departmentId: null,
      departmentName: 'Academic Administration',
      designation: 'Dean of Academic Affairs',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      phone: '+91 94440 99881',
      leaveCasual: 10,
      leaveMedical: 8,
      leaveEarned: 12,
      leaveTotal: 30,
    },
    {
      id: 'usr-arun',
      email: 'arun.kumar@takshashila.edu',
      name: 'Dr. Arun Kumar',
      role: 'FACULTY',
      facultyId: 'FAC-CSE-014',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      designation: 'Associate Professor',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      phone: '+91 98765 43210',
      leaveCasual: 6,
      leaveMedical: 5,
      leaveEarned: 3,
      leaveTotal: 14,
    },
    {
      id: 'usr-priya',
      email: 'priya.menon@takshashila.edu',
      name: 'Prof. S. Menon',
      role: 'FACULTY',
      facultyId: 'FAC-CSE-008',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      designation: 'Professor',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      phone: '+91 98840 55667',
      leaveCasual: 1,
      leaveMedical: 0,
      leaveEarned: 4,
      leaveTotal: 5,
    },
    {
      id: 'usr-meera',
      email: 'meera.nambiar@takshashila.edu',
      name: 'Dr. Meera Nambiar',
      role: 'FACULTY',
      facultyId: 'FAC-CSE-021',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      designation: 'Assistant Professor',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      phone: '+91 98451 22334',
      leaveCasual: 5,
      leaveMedical: 4,
      leaveEarned: 2,
      leaveTotal: 11,
    },
    {
      id: 'usr-raman',
      email: 'kv.raman@takshashila.edu',
      name: 'Prof. K. V. Raman',
      role: 'FACULTY',
      facultyId: 'FAC-CSE-005',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      designation: 'Professor',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      phone: '+91 98452 33445',
      leaveCasual: 8,
      leaveMedical: 5,
      leaveEarned: 3,
      leaveTotal: 16,
    },
    {
      id: 'usr-sunita',
      email: 'sunita.rao@takshashila.edu',
      name: 'Dr. Sunita Rao',
      role: 'FACULTY',
      facultyId: 'FAC-CSE-011',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      designation: 'Associate Professor',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      phone: '+91 98453 44556',
      leaveCasual: 4,
      leaveMedical: 3,
      leaveEarned: 2,
      leaveTotal: 9,
    },
    {
      id: 'usr-malini',
      email: 'malini.venkat@takshashila.edu',
      name: 'Prof. Malini Venkat',
      role: 'FACULTY',
      facultyId: 'FAC-CSE-019',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      designation: 'Assistant Professor',
      avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
      phone: '+91 98454 55667',
      leaveCasual: 7,
      leaveMedical: 5,
      leaveEarned: 3,
      leaveTotal: 15,
    },
    {
      id: 'usr-nitin',
      email: 'nitin.deshmukh@takshashila.edu',
      name: 'Dr. Nitin Deshmukh',
      role: 'FACULTY',
      facultyId: 'FAC-CSE-026',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      designation: 'Assistant Professor',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      phone: '+91 98455 66778',
      leaveCasual: 6,
      leaveMedical: 4,
      leaveEarned: 3,
      leaveTotal: 13,
    },
    {
      id: 'usr-bhavna',
      email: 'bhavna.roy@takshashila.edu',
      name: 'Dr. Bhavna Roy',
      role: 'FACULTY',
      facultyId: 'FAC-CSE-033',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      designation: 'Assistant Professor',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      phone: '+91 98456 77889',
      leaveCasual: 5,
      leaveMedical: 3,
      leaveEarned: 2,
      leaveTotal: 10,
    },
  ]).onConflictDoNothing();

  // 3. Faculty Directory
  console.log('Seeding faculty profiles...');
  await db.insert(faculty).values([
    {
      id: 'usr-rajesh',
      facultyId: 'FAC-CSE-001',
      name: 'Dr. Rajesh Sharma',
      email: 'rajesh.sharma@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Assoc. Professor & HOD',
      status: 'Present',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      specialization: ['Database Systems', 'Cloud Computing', 'Distributed Systems'],
      classesToday: 3,
      attendanceRate: 98,
      leaveBalance: 12,
    },
    {
      id: 'usr-arun',
      facultyId: 'FAC-CSE-014',
      name: 'Dr. Arun Kumar',
      email: 'arun.kumar@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Associate Professor',
      status: 'On Leave',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      specialization: ['Data Structures & Algorithms', 'Discrete Mathematics'],
      classesToday: 0,
      attendanceRate: 94,
      leaveBalance: 14,
    },
    {
      id: 'usr-priya',
      facultyId: 'FAC-CSE-008',
      name: 'Prof. S. Menon',
      email: 'priya.menon@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Professor',
      status: 'On Leave',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      specialization: ['Advanced Algorithms', 'Graph Theory', 'Automata'],
      classesToday: 0,
      attendanceRate: 88,
      leaveBalance: 5,
    },
    {
      id: 'usr-meera',
      facultyId: 'FAC-CSE-021',
      name: 'Dr. Meera Nambiar',
      email: 'meera.nambiar@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Assistant Professor',
      status: 'Present',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      specialization: ['Computer Networks', 'Network Security', 'Cryptography'],
      classesToday: 2,
      attendanceRate: 96,
      leaveBalance: 11,
    },
    {
      id: 'usr-raman',
      facultyId: 'FAC-CSE-005',
      name: 'Prof. K. V. Raman',
      email: 'kv.raman@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Professor',
      status: 'Present',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      specialization: ['Compiler Design', 'Formal Languages', 'System Software'],
      classesToday: 2,
      attendanceRate: 99,
      leaveBalance: 16,
    },
    {
      id: 'usr-sunita',
      facultyId: 'FAC-CSE-011',
      name: 'Dr. Sunita Rao',
      email: 'sunita.rao@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Associate Professor',
      status: 'Present',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      specialization: ['Artificial Intelligence', 'Machine Learning', 'Deep Learning'],
      classesToday: 1,
      attendanceRate: 95,
      leaveBalance: 9,
    },
    {
      id: 'usr-malini',
      facultyId: 'FAC-CSE-019',
      name: 'Prof. Malini Venkat',
      email: 'malini.venkat@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Assistant Professor',
      status: 'Present',
      avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
      specialization: ['Web Technologies', 'Software Engineering', 'UI/UX Design'],
      classesToday: 2,
      attendanceRate: 93,
      leaveBalance: 15,
    },
    {
      id: 'usr-nitin',
      facultyId: 'FAC-CSE-026',
      name: 'Dr. Nitin Deshmukh',
      email: 'nitin.deshmukh@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Assistant Professor',
      status: 'Present',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      specialization: ['Embedded Systems', 'IoT Architecture', 'Robotics'],
      classesToday: 2,
      attendanceRate: 97,
      leaveBalance: 13,
    },
    {
      id: 'usr-bhavna',
      facultyId: 'FAC-CSE-033',
      name: 'Dr. Bhavna Roy',
      email: 'bhavna.roy@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Assistant Professor',
      status: 'Present',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      specialization: ['Cybersecurity', 'Ethical Hacking', 'Blockchain'],
      classesToday: 1,
      attendanceRate: 92,
      leaveBalance: 10,
    },
  ]).onConflictDoNothing();

  // 4. Subjects
  console.log('Seeding subjects...');
  await db.insert(subjects).values([
    {
      id: 'sub-cs201',
      code: 'CS-201',
      name: 'Data Structures & Algorithms',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 4,
      semester: 'Semester 3',
      type: 'Core',
      weeklyHours: 4,
      syllabusSummary: 'Linear and non-linear data structures, asymptotic notation, sorting algorithms, graphs and trees.',
    },
    {
      id: 'sub-cs202',
      code: 'CS-202',
      name: 'Database Management Systems',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 4,
      semester: 'Semester 4',
      type: 'Core',
      weeklyHours: 4,
      syllabusSummary: 'Relational model, SQL, normalization, transaction processing, concurrency control, ACID properties.',
    },
    {
      id: 'sub-cs202p',
      code: 'CS-202P',
      name: 'Python Programming Lab',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 2,
      semester: 'Semester 4',
      type: 'Core',
      weeklyHours: 3,
      syllabusSummary: 'Hands-on programming with Python, data structures, scientific computing and test-driven development.',
    },
    {
      id: 'sub-cs301',
      code: 'CS-301',
      name: 'Operating Systems & Architecture',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 4,
      semester: 'Semester 5',
      type: 'Core',
      weeklyHours: 4,
      syllabusSummary: 'Process synchronization, CPU scheduling, memory management, virtual memory, file system design.',
    },
    {
      id: 'sub-cs302',
      code: 'CS-302',
      name: 'Data Structures & Algorithms',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 4,
      semester: 'Semester 3',
      type: 'Core',
      weeklyHours: 4,
      syllabusSummary: 'Advanced algorithmic paradigms, graph theory, greedy strategies and dynamic programming.',
    },
    {
      id: 'sub-cs303p',
      code: 'CS-303P',
      name: 'Data Structures Lab',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 2,
      semester: 'Semester 3',
      type: 'Core',
      weeklyHours: 3,
      syllabusSummary: 'Implementation and performance profiling of balanced search trees, heaps, and graph search.',
    },
    {
      id: 'sub-cs401',
      code: 'CS-401',
      name: 'Compiler Design & Formal Languages',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 4,
      semester: 'Semester 7',
      type: 'Core',
      weeklyHours: 3,
      syllabusSummary: 'Lexical analysis, syntax analysis, context-free grammars, intermediate code generation, optimization.',
    },
    {
      id: 'sub-cs402',
      code: 'CS-402',
      name: 'Cloud Computing & Distributed Systems',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 3,
      semester: 'Semester 7',
      type: 'Elective',
      weeklyHours: 3,
      syllabusSummary: 'Virtualization, microservices, consensus protocols, distributed storage, container orchestration.',
    },
    {
      id: 'sub-cs504p',
      code: 'CS-504P',
      name: 'Machine Learning Practical',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 2,
      semester: 'Semester 5',
      type: 'Core',
      weeklyHours: 3,
      syllabusSummary: 'Supervised and unsupervised models, PyTorch pipeline implementation, evaluation and validation metrics.',
    },
    {
      id: 'sub-cs601',
      code: 'CS-601',
      name: 'Advanced Algorithms',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 4,
      semester: 'Semester 6',
      type: 'Core',
      weeklyHours: 4,
      syllabusSummary: 'Approximation algorithms, NP-completeness reductions, randomized algorithms and network flow.',
    },
    {
      id: 'sub-cs603',
      code: 'CS-603',
      name: 'Cloud Computing Architecture',
      departmentId: 'dept-cse',
      departmentName: 'Department of Computer Science & Engineering',
      credits: 4,
      semester: 'Semester 7',
      type: 'Core',
      weeklyHours: 4,
      syllabusSummary: 'Infrastructure as Code, Kubernetes clusters, fault-tolerance and distributed consensus architectures.',
    },
    {
      id: 'sub-ec201',
      code: 'EC-201',
      name: 'Digital Signal Processing',
      departmentId: 'dept-ece',
      departmentName: 'Department of Electronics & Communication',
      credits: 4,
      semester: 'Semester 4',
      type: 'Core',
      weeklyHours: 4,
      syllabusSummary: 'DFT, FFT, FIR and IIR filter design, multi-rate signal processing.',
    },
    {
      id: 'sub-mg101',
      code: 'MG-101',
      name: 'Principles of Organizational Management',
      departmentId: 'dept-mgmt',
      departmentName: 'Department of Management Studies',
      credits: 3,
      semester: 'Semester 2',
      type: 'Core',
      weeklyHours: 3,
      syllabusSummary: 'Organizational behavior, strategic planning, human resource management, leadership theories.',
    },
    {
      id: 'sub-cm201',
      code: 'CM-201',
      name: 'Advanced Corporate Accounting',
      departmentId: 'dept-comm',
      departmentName: 'Department of Commerce & Accounting',
      credits: 4,
      semester: 'Semester 4',
      type: 'Core',
      weeklyHours: 4,
      syllabusSummary: 'Valuation of goodwill and shares, liquidation accounts, holding company accounts.',
    },
  ]).onConflictDoNothing();

  // 5. Classrooms
  console.log('Seeding classrooms...');
  await db.insert(classrooms).values([
    {
      id: 'cls-room-204',
      roomNumber: 'Room 204',
      building: 'Aryabhata Academic Block',
      floor: 2,
      capacity: 70,
      type: 'Smart Lecture Hall',
      facilities: ['Smart Interactive Board', 'Dual 4K Projectors', 'Wireless Mic', 'Central Air Conditioning'],
      status: 'Available',
    },
    {
      id: 'cls-room-301',
      roomNumber: 'Room 301',
      building: 'Aryabhata Academic Block',
      floor: 3,
      capacity: 65,
      type: 'Smart Lecture Hall',
      facilities: ['Interactive Touch Display', 'Document Camera', 'Audio System', 'AC'],
      status: 'Available',
    },
    {
      id: 'cls-room-305',
      roomNumber: 'Room 305',
      building: 'Aryabhata Academic Block',
      floor: 3,
      capacity: 70,
      type: 'Smart Lecture Hall',
      facilities: ['Dual 4K Projectors', 'Lapel Audio System', 'Smart Board', 'AC'],
      status: 'Available',
    },
    {
      id: 'cls-cs-lab2',
      roomNumber: 'Computing Lab 2',
      building: 'Turing Computing Complex',
      floor: 1,
      capacity: 60,
      type: 'Computer Lab',
      facilities: ['60 High-Performance Workstations', 'Gigabit Ethernet', 'UPS Backup', 'Overhead Projector', 'AC'],
      status: 'Available',
    },
    {
      id: 'cls-cs-lab4',
      roomNumber: 'Computing Lab 4',
      building: 'Turing Computing Complex',
      floor: 2,
      capacity: 60,
      type: 'Computer Lab',
      facilities: ['60 Workstations', 'GPU Compute Cluster Access', 'Dual Projectors', 'AC'],
      status: 'Available',
    },
    {
      id: 'cls-sem-aud-b',
      roomNumber: 'Auditorium B',
      building: 'Chanakya Central Complex',
      floor: 1,
      capacity: 200,
      type: 'Auditorium',
      facilities: ['Surround Sound Audio', 'Stage Lighting', 'Lecture Capture System', 'Full AC'],
      status: 'Available',
    },
  ]).onConflictDoNothing();

  // 6. Leave Types
  console.log('Seeding leave types...');
  await db.insert(leaveTypes).values([
    {
      id: 'lt-cl',
      name: 'Casual Leave',
      code: 'CL',
      defaultQuota: 12,
      description: 'For personal urgent affairs, short family duties, or unforeseen exigencies.',
      requiresDocument: false,
    },
    {
      id: 'lt-ml',
      name: 'Medical Leave',
      code: 'ML',
      defaultQuota: 10,
      description: 'For certified illness or medical treatment, subject to medical certificate for >2 days.',
      requiresDocument: true,
    },
    {
      id: 'lt-el',
      name: 'Earned Leave',
      code: 'EL',
      defaultQuota: 15,
      description: 'Earned annual vacation leave credited based on completed active teaching tenure.',
      requiresDocument: false,
    },
    {
      id: 'lt-dl',
      name: 'Duty Leave',
      code: 'DL',
      defaultQuota: 15,
      description: 'For attending academic conferences, doctoral evaluations, syllabus revisions, or university delegations.',
      requiresDocument: true,
    },
  ]).onConflictDoNothing();

  // 7. Full Weekly Timetable (Monday to Friday)
  console.log('Seeding full weekly timetable...');
  await db.insert(timetableSlots).values([
    // Monday
    {
      id: 'slot-mon-1',
      dayOfWeek: 'Monday',
      startTime: '09:00 AM',
      endTime: '10:00 AM',
      subjectCode: 'CS-302',
      subjectName: 'Data Structures & Algorithms',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE II',
      semester: 'Semester 3',
      classroom: 'Room 204',
      facultyId: 'usr-arun',
      facultyName: 'Dr. Arun Kumar',
      status: 'SCHEDULED',
      enrolledStudents: 62,
      notes: 'Binary Trees & Priority Queues',
    },
    {
      id: 'slot-mon-2',
      dayOfWeek: 'Monday',
      startTime: '11:00 AM',
      endTime: '12:00 PM',
      subjectCode: 'CS-201',
      subjectName: 'Data Structures',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE II',
      semester: 'Semester 3',
      classroom: 'Room 305',
      facultyId: 'usr-rajesh',
      facultyName: 'Dr. Rajesh Sharma',
      status: 'SCHEDULED',
      enrolledStudents: 60,
      notes: 'Object Oriented Software Architecture',
    },
    {
      id: 'slot-mon-3',
      dayOfWeek: 'Monday',
      startTime: '02:00 PM',
      endTime: '04:00 PM',
      subjectCode: 'CS-303P',
      subjectName: 'Data Structures Lab',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE II',
      semester: 'Semester 3',
      classroom: 'Computing Lab 2',
      facultyId: 'usr-arun',
      facultyName: 'Dr. Arun Kumar',
      status: 'SCHEDULED',
      enrolledStudents: 32,
      notes: 'AVL Trees & Balance Factor verification',
    },

    // Tuesday
    {
      id: 'slot-1',
      dayOfWeek: 'Tuesday',
      startTime: '09:00 AM',
      endTime: '10:00 AM',
      subjectCode: 'CS-201',
      subjectName: 'Data Structures',
      department: 'Computer Science & Engineering',
      section: 'B.Tech CSE II',
      semester: 'Semester 3',
      classroom: 'Room 204',
      facultyId: 'usr-rajesh',
      facultyName: 'Dr. Rajesh Sharma',
      status: 'COMPLETED',
      enrolledStudents: 62,
      notes: 'Arrays, Stacks, and Queue Implementation verified',
    },
    {
      id: 'slot-2',
      dayOfWeek: 'Tuesday',
      startTime: '11:00 AM',
      endTime: '12:00 PM',
      subjectCode: 'CS-301',
      subjectName: 'Database Management Systems',
      department: 'Computer Science & Engineering',
      section: 'B.Tech CSE III',
      semester: 'Semester 5',
      classroom: 'Room 305',
      facultyId: 'usr-rajesh',
      facultyName: 'Dr. Rajesh Sharma',
      status: 'IN_PROGRESS',
      enrolledStudents: 58,
      notes: 'Module 4: Normalization (3NF & BCNF)',
    },
    {
      id: 'slot-3',
      dayOfWeek: 'Tuesday',
      startTime: '02:00 PM',
      endTime: '04:00 PM',
      subjectCode: 'CS-202P',
      subjectName: 'Python Programming Lab',
      department: 'Computer Science & Engineering',
      section: 'B.Tech CSE IV',
      semester: 'Semester 4',
      classroom: 'Computing Lab 4',
      facultyId: 'usr-rajesh',
      facultyName: 'Dr. Rajesh Sharma',
      status: 'SCHEDULED',
      enrolledStudents: 30,
      notes: 'Workstations Synced • Lab Test evaluation',
    },
    {
      id: 'slot-4',
      dayOfWeek: 'Tuesday',
      startTime: '01:00 PM',
      endTime: '02:00 PM',
      subjectCode: 'CS-401',
      subjectName: 'Compiler Design',
      department: 'Computer Science & Engineering',
      section: 'B.Tech CSE IV',
      semester: 'Semester 7',
      classroom: 'Room 301',
      facultyId: 'usr-raman',
      facultyName: 'Prof. K. V. Raman',
      status: 'IN_PROGRESS',
      enrolledStudents: 52,
      notes: '48 / 52 attended',
    },
    {
      id: 'slot-5',
      dayOfWeek: 'Tuesday',
      startTime: '02:00 PM',
      endTime: '03:00 PM',
      subjectCode: 'CS-302',
      subjectName: 'Data Structures & Algorithms',
      department: 'Computer Science & Engineering',
      section: 'B.Tech CSE II',
      semester: 'Semester 3',
      classroom: 'Room 204',
      facultyId: 'usr-arun',
      facultyName: 'Dr. Arun Kumar',
      status: 'SUBSTITUTION_PENDING',
      enrolledStudents: 62,
      notes: 'Originally: Dr. Arun Kumar (On Leave) • Medical emergency',
    },
    {
      id: 'slot-6',
      dayOfWeek: 'Tuesday',
      startTime: '02:30 PM',
      endTime: '04:30 PM',
      subjectCode: 'CS-504P',
      subjectName: 'Machine Learning Practical',
      department: 'Computer Science & Engineering',
      section: 'B.Tech CSE III',
      semester: 'Semester 5',
      classroom: 'Computing Lab 4',
      facultyId: 'usr-sunita',
      facultyName: 'Dr. Sunita Rao',
      status: 'SCHEDULED',
      enrolledStudents: 45,
      notes: 'Assigned: Dr. Sunita Rao & 2 TAs (Ready)',
    },
    {
      id: 'slot-7',
      dayOfWeek: 'Tuesday',
      startTime: '03:30 PM',
      endTime: '04:30 PM',
      subjectCode: 'CS-603',
      subjectName: 'Cloud Computing Architecture',
      department: 'Computer Science & Engineering',
      section: 'B.Tech CSE IV',
      semester: 'Semester 7',
      classroom: 'Auditorium B',
      facultyId: 'usr-rajesh',
      facultyName: 'Dr. Rajesh Sharma',
      status: 'SCHEDULED',
      enrolledStudents: 75,
      notes: 'HOD Special Lecture',
    },

    // Wednesday
    {
      id: 'slot-wed-1',
      dayOfWeek: 'Wednesday',
      startTime: '09:00 AM',
      endTime: '10:00 AM',
      subjectCode: 'CS-302',
      subjectName: 'Data Structures & Algorithms',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE II',
      semester: 'Semester 3',
      classroom: 'Room 204',
      facultyId: 'usr-arun',
      facultyName: 'Dr. Arun Kumar',
      status: 'SCHEDULED',
      enrolledStudents: 62,
      notes: 'Graph Algorithms: DFS and BFS',
    },
    {
      id: 'slot-wed-2',
      dayOfWeek: 'Wednesday',
      startTime: '10:30 AM',
      endTime: '11:30 AM',
      subjectCode: 'CS-301',
      subjectName: 'Database Management Systems',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE III',
      semester: 'Semester 5',
      classroom: 'Room 305',
      facultyId: 'usr-rajesh',
      facultyName: 'Dr. Rajesh Sharma',
      status: 'SCHEDULED',
      enrolledStudents: 58,
      notes: 'Transaction Management & ACID properties',
    },
    {
      id: 'slot-wed-3',
      dayOfWeek: 'Wednesday',
      startTime: '02:00 PM',
      endTime: '03:00 PM',
      subjectCode: 'CS-401',
      subjectName: 'Compiler Design',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE IV',
      semester: 'Semester 7',
      classroom: 'Room 301',
      facultyId: 'usr-raman',
      facultyName: 'Prof. K. V. Raman',
      status: 'SCHEDULED',
      enrolledStudents: 52,
      notes: 'Lexical analysis & DFA construction',
    },

    // Thursday
    {
      id: 'slot-thu-1',
      dayOfWeek: 'Thursday',
      startTime: '09:00 AM',
      endTime: '10:00 AM',
      subjectCode: 'CS-201',
      subjectName: 'Data Structures',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE II',
      semester: 'Semester 3',
      classroom: 'Room 204',
      facultyId: 'usr-rajesh',
      facultyName: 'Dr. Rajesh Sharma',
      status: 'SCHEDULED',
      enrolledStudents: 62,
      notes: 'Shortest path algorithms (Dijkstra)',
    },
    {
      id: 'slot-thu-2',
      dayOfWeek: 'Thursday',
      startTime: '11:00 AM',
      endTime: '12:00 PM',
      subjectCode: 'CS-302',
      subjectName: 'Data Structures & Algorithms',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE II',
      semester: 'Semester 3',
      classroom: 'Room 204',
      facultyId: 'usr-arun',
      facultyName: 'Dr. Arun Kumar',
      status: 'SCHEDULED',
      enrolledStudents: 62,
      notes: 'Minimum Spanning Trees: Kruskal & Prim',
    },
    {
      id: 'slot-thu-3',
      dayOfWeek: 'Thursday',
      startTime: '02:00 PM',
      endTime: '04:00 PM',
      subjectCode: 'CS-202P',
      subjectName: 'Python Programming Lab',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE II',
      semester: 'Semester 3',
      classroom: 'Computing Lab 4',
      facultyId: 'usr-rajesh',
      facultyName: 'Dr. Rajesh Sharma',
      status: 'SCHEDULED',
      enrolledStudents: 30,
      notes: 'Data pipeline engineering & unit testing',
    },

    // Friday
    {
      id: 'slot-fri-1',
      dayOfWeek: 'Friday',
      startTime: '09:00 AM',
      endTime: '10:00 AM',
      subjectCode: 'CS-302',
      subjectName: 'Algorithms Problem Solving',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE II',
      semester: 'Semester 3',
      classroom: 'Room 204',
      facultyId: 'usr-arun',
      facultyName: 'Dr. Arun Kumar',
      status: 'SCHEDULED',
      enrolledStudents: 62,
      notes: 'Dynamic Programming & Memoization',
    },
    {
      id: 'slot-fri-2',
      dayOfWeek: 'Friday',
      startTime: '11:00 AM',
      endTime: '12:00 PM',
      subjectCode: 'CS-603',
      subjectName: 'Cloud Computing Architecture',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE IV',
      semester: 'Semester 7',
      classroom: 'Auditorium B',
      facultyId: 'usr-rajesh',
      facultyName: 'Dr. Rajesh Sharma',
      status: 'SCHEDULED',
      enrolledStudents: 75,
      notes: 'Kubernetes ingress & Service meshes',
    },
    {
      id: 'slot-fri-3',
      dayOfWeek: 'Friday',
      startTime: '02:00 PM',
      endTime: '04:00 PM',
      subjectCode: 'CS-504P',
      subjectName: 'Machine Learning Practical',
      department: 'Department of Computer Science & Engineering',
      section: 'B.Tech CSE III',
      semester: 'Semester 5',
      classroom: 'Computing Lab 4',
      facultyId: 'usr-sunita',
      facultyName: 'Dr. Sunita Rao',
      status: 'SCHEDULED',
      enrolledStudents: 45,
      notes: 'Transfer learning on Vision Transformers',
    },
  ]).onConflictDoNothing();

  // 8. Leave Requests
  console.log('Seeding leave requests...');
  await db.insert(leaveRequests).values([
    {
      id: 'leave-101',
      facultyId: 'usr-arun',
      facultyName: 'Dr. Arun Kumar',
      facultyEmail: 'arun.kumar@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Associate Professor',
      leaveType: 'Casual Leave',
      startDate: '2026-09-18',
      endDate: '2026-09-20',
      daysCount: 3,
      reason: 'Doctoral defense external examiner at IISc Bengaluru for thesis committee evaluation.',
      status: 'PENDING',
      attachmentName: 'IISc_Invitation_Letter.pdf',
    },
    {
      id: 'leave-102',
      facultyId: 'usr-priya',
      facultyName: 'Prof. S. Menon',
      facultyEmail: 'priya.menon@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Professor',
      leaveType: 'Medical Leave',
      startDate: '2026-09-16',
      endDate: '2026-09-18',
      daysCount: 3,
      reason: 'Hospitalization and recuperation due to viral pneumonia.',
      status: 'APPROVED',
      reviewedBy: 'Dr. Rajesh Sharma',
      reviewRemarks: 'Approved as Casual/Medical Grant. Please arrange substitute lectures.',
    },
    {
      id: 'leave-103',
      facultyId: 'usr-rajesh',
      facultyName: 'Dr. Rajesh Sharma',
      facultyEmail: 'rajesh.sharma@takshashila.edu',
      department: 'Computer Science & Engineering',
      designation: 'Assoc. Professor & HOD',
      leaveType: 'On Duty',
      startDate: '2026-09-28',
      endDate: '2026-09-29',
      daysCount: 2,
      reason: 'Keynote Speaker at IEEE International Conference on Cloud Paradigms.',
      status: 'APPROVED',
      reviewedBy: 'Dr. K. S. Somnath',
      reviewRemarks: 'OD sanctioned. All classes to be pre-recorded or compensated.',
    },
  ]).onConflictDoNothing();

  // 9. Alternative Classes
  console.log('Seeding alternative classes...');
  await db.insert(alternativeClasses).values([
    {
      id: 'alt-201',
      leaveRequestId: 'leave-102',
      originalFacultyId: 'usr-priya',
      originalFacultyName: 'Prof. S. Menon',
      subjectCode: 'CS-601',
      subjectName: 'Advanced Algorithms',
      date: '2026-09-16',
      startTime: '03:00 PM',
      endTime: '04:00 PM',
      classroom: 'Room 204',
      section: 'B.Tech CSE Sem 6',
      reason: 'Replaced: Prof. S. Menon (On Medical Leave)',
      assignedFacultyId: 'usr-rajesh',
      assignedFacultyName: 'Dr. Rajesh Sharma',
      status: 'OFFERED_TO_FACULTY',
      notes: 'Response requested by 1:30 PM',
    },
    {
      id: 'alt-202',
      leaveRequestId: 'leave-101',
      originalFacultyId: 'usr-arun',
      originalFacultyName: 'Dr. Arun Kumar',
      subjectCode: 'CS-302',
      subjectName: 'Data Structures & Algorithms',
      date: '2026-09-16',
      startTime: '02:00 PM',
      endTime: '03:00 PM',
      classroom: 'Room 204',
      section: 'B.Tech CSE II',
      reason: 'Medical emergency & conference absence',
      status: 'PENDING_FACULTY_ASSIGNMENT',
      notes: '62 Enrolled Students • Needs immediate substitute',
    },
  ]).onConflictDoNothing();

  // 10. Notifications
  console.log('Seeding notifications...');
  await db.insert(notifications).values([
    {
      id: 'notif-1',
      userId: 'usr-rajesh',
      title: 'Substitute session requested',
      message: 'Advanced Algorithms (B.Tech CSE Sem 6) at 03:00 PM in Room 204. Replaced: Prof. S. Menon (On Medical Leave).',
      type: 'substitution',
      read: false,
      timestamp: 'Today at 08:30 AM',
      actionUrl: '/classes',
      actionPayload: { altId: 'alt-201' },
    },
    {
      id: 'notif-2',
      userId: 'usr-rajesh',
      title: 'Medical Leave approved by HOD',
      message: 'Casual Leave Grant for Prof. S. Menon processed and archived.',
      type: 'leave',
      read: true,
      timestamp: 'Yesterday at 4:15 PM',
    },
    {
      id: 'notif-3',
      userId: 'usr-rajesh',
      title: 'Timetable swap confirmed for Friday',
      message: 'Exchanged afternoon lab slot with Prof. S. Sen for upcoming NAAC accreditation prep.',
      type: 'timetable',
      read: true,
      timestamp: 'Oct 20 at 11:20 AM',
    },
    {
      id: 'notif-4',
      userId: 'usr-rajesh',
      title: 'Curriculum Review Meeting',
      message: 'Thursday, Oct 26 at 04:30 PM in Senate Hall. Agendas uploaded to academic drive.',
      type: 'announcement',
      read: true,
      timestamp: 'Oct 19 at 02:00 PM',
    },
    {
      id: 'notif-5',
      userId: 'usr-rajesh',
      title: 'New Leave Request: Dr. Arun Kumar',
      message: 'Dr. Arun Kumar has applied for Casual Leave (3 days, 18–20 Sep). Review required.',
      type: 'leave',
      read: false,
      timestamp: 'Today at 09:35 AM',
      actionUrl: '/leave',
    },
  ]).onConflictDoNothing();

  // 11. Audit Logs
  console.log('Seeding audit logs...');
  await db.insert(auditLogs).values([
    {
      id: 'audit-1',
      userId: 'usr-rajesh',
      userName: 'Dr. Rajesh Sharma',
      action: 'SUBSTITUTION_OFFERED',
      module: 'SUBSTITUTION',
      details: 'Offered substitute class CS-601 to Dr. Rajesh Sharma for Prof. S. Menon on medical leave',
      metadata: { altId: 'alt-201' },
    },
    {
      id: 'audit-2',
      userId: 'usr-arun',
      userName: 'Dr. Arun Kumar',
      action: 'LEAVE_SUBMITTED',
      module: 'LEAVE',
      details: 'Submitted Casual Leave for 3 days (18–20 Sep) - IISc external doctoral defense',
      metadata: { leaveId: 'leave-101' },
    },
    {
      id: 'audit-3',
      userId: 'usr-rajesh',
      userName: 'Dr. Rajesh Sharma',
      action: 'LEAVE_APPROVED',
      module: 'LEAVE',
      details: 'Approved Medical Leave request for Prof. S. Menon (3 days)',
      metadata: { leaveId: 'leave-102' },
    },
    {
      id: 'audit-4',
      userId: 'usr-admin',
      userName: 'Dr. K. S. Somnath',
      action: 'TIMETABLE_PUBLISHED',
      module: 'TIMETABLE',
      details: 'Fall Semester 2026 Academic Timetable validated and published across all departments',
    },
  ]).onConflictDoNothing();

  console.log('Controlled database seeding successfully completed.');
}

// Auto-run if executed as standalone script via `tsx src/db/seed.ts` or `npm run seed`
const isCLI = process.argv[1]?.includes('seed.ts') || process.argv[1]?.includes('seed.js');
if (isCLI) {
  seedDatabase()
    .then(async () => {
      await pool.end();
      process.exit(0);
    })
    .catch(async (err) => {
      console.error('Controlled database seed encountered an error:', err);
      await pool.end();
      process.exit(1);
    });
}
